# Site settings
title: 红树林
SEOTitle: 红树林
header-img: img/earth-2.jpg
email: 1756563255@qq.com
description: "浪漫主义者丛林"
keyword: "红树林, mangrove, 博客, earthstrider"
url: https://earthstrider.github.io          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/earthstrider/earthstrider.github.io.git" # you code repository

# Sidebar settings
sidebar: False                           # whether or not using Sidebar.
sidebar-about-description: "earthstrider"
sidebar-avatar: /img/me.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: False
# weibo_username:     qiubaiying
# zhihu_username:     qiubaiying
# github_username:    earthstrider
# facebook_username:  baiying.qiu.7
# jianshu_username:   e71990ada2fd
# twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# The 'gems' configuration option has been renamed to 'plugins'.
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
#  enable_coderay: true


# 评论系统
disqus_enable: true
disqus_username: earthstrider-github-io


# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID: dfdfddde0e76ebada022                            #生成的clientID
  clientSecret: e07e1dce6f6776214772bcef515b30ba9347312f    #生成的clientSecret
  repo: earthstrider.github.io    #仓库名称
  owner: earthstrider    #github用户名
  admin: earthstrider
  distractionFreeMode: true #是否启用类似FB的阴影遮罩
  id: 'window.location.pathname'


# 搜索
simple_jekyll_search:
    fulltext: false  # 全文搜索
    limit: 10  # 最多显示多少条搜索结果


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: e4967b9bf133cbc21d19afe9ee81f9fb

# Google Analytics
# ga_track_id: 'UA-122928419-1'            # Format: UA-xxxxxx-xx
# ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: false                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: false



#World's top universities
#friends: [
#    {
#        title: "Datawhale"
#
#    }
    #  {
    #      title: "HKUST",
    #      href: "https://www.ust.hk/",
    #  },{
    #      title: "MIT",
    #      href: "http://web.mit.edu/",
    #  },{
    #      title: "Stanford",
    #      href: "https://www.stanford.edu/",
    #  }
#]

# theme: jekyll-theme-modernist


# sitemap
sitemap:
    filename: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
        - "/offline.html"
        - "/404.html"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
